name: Demo-Library CI

on:
  push:
    branches: [main, demo-branch]
    paths:
      [
        "projects/demo-library/src/**",
        "projects/demo-library/package.json",
        ".github/workflows/demo-library-ci.yml",
      ]

  # Triggers workflow on pull-request events
  # pull_request:
  #     branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  dir: projects/demo-library

jobs:
  demo-library-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: ${{env.dir}}/package-lock.json

      - name: Install project dependencies
        run: npm install

      - name: Install library dependencies
        run: |
          cd ${{env.dir}}
          npm install

      - name: Lint
        run: |
          cd ${{env.dir}}
          npm run lint

      - name: Build
        run: |
          cd ${{env.dir}}
          npm run build-dev

      - name: Test
        run: |
          cd ${{env.dir}}
          npm run test-ci
